apiVersion: v1 
kind: Pod
metadata:
  name: pod-volume
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      volumeMounts:
        - mountPath: /volume-dentro-do-container
          name: segundo-volume
  volumes:
    - name: segundo-volume
      hostPath:
        path: /home/deividandrade/segundo-volume
        type: DirectoryOrCreate
